"""
Chat export module for DocuMind AI.
Converts the current Streamlit Q&A session to a downloadable PDF.
"""

from __future__ import annotations

import datetime
import io
import re
from typing import Dict, List

from loguru import logger
from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
    Paragraph,
)

# ---------------------------------------------------------------------------
# Colour palette (consistent with existing proposal PDFs)
# ---------------------------------------------------------------------------
NAVY   = HexColor("#0D1B2A")
BLUE   = HexColor("#1B4F8A")
GOLD   = HexColor("#F0A500")
GREEN  = HexColor("#1A7A4A")
WHITE  = HexColor("#FFFFFF")
GRAY   = HexColor("#6B7280")
LGRAY  = HexColor("#F3F6FA")
LINE   = HexColor("#DDE3EC")
TEXT   = HexColor("#1A1A2E")
Q_BG   = HexColor("#EEF4FF")
A_BG   = HexColor("#FAFAFA")

W, H = A4


# ---------------------------------------------------------------------------
# Styles
# ---------------------------------------------------------------------------
def _make_styles() -> dict:
    return {
        "title": ParagraphStyle(
            "title", fontName="Helvetica-Bold", fontSize=20,
            textColor=NAVY, spaceAfter=3,
        ),
        "subtitle": ParagraphStyle(
            "subtitle", fontName="Helvetica", fontSize=11,
            textColor=BLUE, spaceAfter=2,
        ),
        "meta_key": ParagraphStyle(
            "meta_key", fontName="Helvetica-Bold", fontSize=9,
            textColor=GRAY, leading=14,
        ),
        "meta_val": ParagraphStyle(
            "meta_val", fontName="Helvetica", fontSize=9,
            textColor=TEXT, leading=14,
        ),
        "q_label": ParagraphStyle(
            "q_label", fontName="Helvetica-Bold", fontSize=8,
            textColor=BLUE, spaceAfter=3,
        ),
        "a_label": ParagraphStyle(
            "a_label", fontName="Helvetica-Bold", fontSize=8,
            textColor=GREEN, spaceAfter=3,
        ),
        "q_text": ParagraphStyle(
            "q_text", fontName="Helvetica-Bold", fontSize=10,
            textColor=TEXT, leading=15, alignment=TA_JUSTIFY,
        ),
        "a_text": ParagraphStyle(
            "a_text", fontName="Helvetica", fontSize=10,
            textColor=TEXT, leading=15, alignment=TA_JUSTIFY,
        ),
        "footer": ParagraphStyle(
            "footer", fontName="Helvetica", fontSize=7,
            textColor=GRAY, alignment=TA_CENTER,
        ),
    }


# ---------------------------------------------------------------------------
# Page header / footer callback
# ---------------------------------------------------------------------------
def _page_chrome(canvas, doc):
    canvas.saveState()

    # ── Header ──────────────────────────────────────────────────────────
    canvas.setFillColor(NAVY)
    canvas.rect(0, H - 12 * mm, W, 12 * mm, fill=1, stroke=0)
    canvas.setFillColor(GOLD)
    canvas.rect(0, H - 12 * mm, 5 * mm, 12 * mm, fill=1, stroke=0)
    canvas.setFillColor(WHITE)
    canvas.setFont("Helvetica-Bold", 8.5)
    canvas.drawString(11 * mm, H - 7.5 * mm, "DocuMind AI  |  Q&A Session Export")
    canvas.setFillColor(HexColor("#A8C4E0"))
    canvas.setFont("Helvetica", 7.5)
    canvas.drawRightString(
        W - 10 * mm,
        H - 7.5 * mm,
        datetime.datetime.now().strftime("%d %b %Y  %H:%M"),
    )

    # ── Footer ──────────────────────────────────────────────────────────
    canvas.setFillColor(LGRAY)
    canvas.rect(0, 0, W, 9 * mm, fill=1, stroke=0)
    canvas.setStrokeColor(LINE)
    canvas.setLineWidth(0.5)
    canvas.line(0, 9 * mm, W, 9 * mm)
    canvas.setFillColor(GRAY)
    canvas.setFont("Helvetica", 7)
    canvas.drawCentredString(
        W / 2, 3.5 * mm,
        "Generated by DocuMind AI  |  alysher-docmind-ai.streamlit.app",
    )
    canvas.setFont("Helvetica-Bold", 7.5)
    canvas.setFillColor(BLUE)
    canvas.drawRightString(W - 18 * mm, 3.5 * mm, f"Page {doc.page}")

    canvas.restoreState()


# ---------------------------------------------------------------------------
# Text helpers
# ---------------------------------------------------------------------------
def _safe_para(text: str, style: ParagraphStyle) -> Paragraph:
    """
    Strip markdown syntax and escape XML special chars before wrapping in Paragraph.
    Converts **bold** to <b>bold</b> so ReportLab renders it correctly.
    """
    # Markdown bold → ReportLab bold tags
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    # Strip remaining lone asterisks / backticks
    text = text.replace("*", "").replace("`", "")
    # Escape XML special characters (but not the <b> tags we just added)
    # Work in segments separated by our own tags
    parts = re.split(r"(<b>.*?</b>)", text)
    escaped = []
    for part in parts:
        if part.startswith("<b>"):
            escaped.append(part)
        else:
            part = part.replace("&", "&amp;")
            part = part.replace("<", "&lt;")
            part = part.replace(">", "&gt;")
            escaped.append(part)
    safe = "".join(escaped)
    # Replace newlines with line breaks
    safe = safe.replace("\n", "<br/>")
    return Paragraph(safe, style)


def _card(content_rows: list, bg: HexColor, border: HexColor, left_accent: HexColor | None = None) -> Table:
    """Render a coloured card table."""
    col_w = W - 36 * mm
    t = Table(content_rows, colWidths=[col_w])
    style_cmds = [
        ("BACKGROUND",    (0, 0), (-1, -1), bg),
        ("LEFTPADDING",   (0, 0), (-1, -1), 10),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 10),
        ("TOPPADDING",    (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("BOX",           (0, 0), (-1, -1), 0.8, border),
    ]
    if left_accent:
        style_cmds.append(("LINEBEFORE", (0, 0), (0, -1), 4, left_accent))
    t.setStyle(TableStyle(style_cmds))
    return t


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def export_chat_to_pdf(
    messages: List[Dict],
    document_name: str = "Unknown Document",
) -> bytes:
    """
    Convert Streamlit session messages to a formatted PDF.

    Args:
        messages:      st.session_state.messages list
        document_name: Name of the uploaded document (for header)

    Returns:
        Raw PDF bytes ready for st.download_button().
    """
    buf = io.BytesIO()

    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=16 * mm,
        title="DocuMind AI — Chat Export",
        author="DocuMind AI",
    )

    s   = _make_styles()
    cw  = W - 36 * mm
    story: list = []

    # ── Cover block ──────────────────────────────────────────────────────
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("DocuMind AI", s["title"]))
    story.append(Paragraph("Q&amp;A Session Export", s["subtitle"]))
    story.append(HRFlowable(width="100%", thickness=2, color=GOLD, spaceAfter=5))
    story.append(Spacer(1, 2 * mm))

    n_exchanges = sum(1 for m in messages if m["role"] == "user")
    now_str     = datetime.datetime.now().strftime("%d %B %Y at %H:%M")

    meta_rows = [
        [Paragraph("Document", s["meta_key"]),  Paragraph(document_name, s["meta_val"])],
        [Paragraph("Exported",  s["meta_key"]),  Paragraph(now_str, s["meta_val"])],
        [Paragraph("Exchanges", s["meta_key"]),  Paragraph(str(n_exchanges), s["meta_val"])],
    ]
    meta_t = Table(meta_rows, colWidths=[cw * 0.22, cw * 0.78])
    meta_t.setStyle(TableStyle([
        ("TOPPADDING",    (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LEFTPADDING",   (0, 0), (-1, -1), 0),
        ("VALIGN",        (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(meta_t)
    story.append(Spacer(1, 5 * mm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=LINE, spaceAfter=4))
    story.append(Spacer(1, 3 * mm))

    # ── Q&A pairs ────────────────────────────────────────────────────────
    q_count = 0
    idx     = 0

    while idx < len(messages):
        msg = messages[idx]

        # Skip the initial greeting
        if msg["role"] == "assistant" and idx == 0:
            idx += 1
            continue

        if msg["role"] == "user":
            q_count += 1

            # Question card
            q_rows = [
                [Paragraph(f"Question {q_count}", s["q_label"])],
                [_safe_para(msg["content"], s["q_text"])],
            ]
            story.append(_card(q_rows, Q_BG, BLUE, BLUE))
            story.append(Spacer(1, 2 * mm))

            # Answer card (next message if it exists and is assistant)
            if idx + 1 < len(messages) and messages[idx + 1]["role"] == "assistant":
                ans = messages[idx + 1]
                complexity = ans.get("complexity", "Balanced")
                complexity_colors = {
                    "Simple":   "#1A7A4A",
                    "Balanced": "#1B4F8A",
                    "Expert":   "#6B3FA0",
                }
                c_color = complexity_colors.get(complexity, "#1B4F8A")
                a_rows = [
                    [Paragraph(
                        f"Answer &nbsp;&nbsp;"
                        f"<font color='{c_color}'><b>[{complexity} Mode]</b></font>",
                        s["a_label"]
                    )],
                    [_safe_para(ans["content"], s["a_text"])],
                ]
                story.append(_card(a_rows, A_BG, LINE, GREEN))
                idx += 2
            else:
                idx += 1

            story.append(Spacer(1, 4 * mm))
            story.append(HRFlowable(width="100%", thickness=0.3, color=LINE, spaceAfter=3))
            story.append(Spacer(1, 3 * mm))
        else:
            idx += 1

    if q_count == 0:
        story.append(Paragraph("No Q&amp;A exchanges in this session.", s["meta_val"]))

    # ── Build ────────────────────────────────────────────────────────────
    doc.build(story, onFirstPage=_page_chrome, onLaterPages=_page_chrome)
    buf.seek(0)

    logger.info(
        f"Chat export PDF built — {q_count} exchange(s) from '{document_name}'"
    )
    return buf.read()
